spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbapp
    username: user
    password: password  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect